### ISSUE TITLE
python3.8以下版本不支持海象表达式 :=

### ISSUE THREAD

**Issue by chacha1024** [synodriver/pyjce#2]
pyjce2-0.1.0-py3.7.egg/pyjce/reader.py", line 152
    if (type_ := head.type) == 12:
              ^
SyntaxError: invalid syntax

**Comment by synodriver** [comment]
使用python3.8以上版本即可解决, 而且这个问题改起来也并不麻烦, 自行修改掉所有的```:=```即可, 一共也就8个,这里就不演示了

**Comment by synodriver** [comment]
有空我用cython重构一下~~也许就没有这个问题了~~

这个问题先留给小朋友来看看
